- hosts: localhost

  tasks:
    - name: Create composer home
      file: path=~/.composer state=directory

    - name: Ensure directory exists
      file:
        path: ~/Work/Tools/composer
        state: directory

    - name: Create composer.sh with function
      copy:
        dest: ~/Work/Tools/composer/composer.sh
        mode: '0755'
        content: |
          #!/bin/bash
          composer () {
            params="--ignore-platform-reqs --no-scripts -vvv"

            if [
              "$1" = "dump-autoload" \
              -o "$1" = "clearcache" \
              -o "$1" = "config" \
              -o "$1" = "outdated" \
              -o "$1" = "fund" \
              -o "$1" = "depends" \
              -o "$1" = "prohibits"
            ]; then
              params=""
            fi

            tty=
            tty -s && tty=--tty

            docker run --rm --interactive --tty \
              --volume $PWD:/app \
              --volume $SSH_AUTH_SOCK:/ssh-auth.sock \
              --volume ~/.composer:/tmp \
              --volume ~/Work/:/home/yosmanyga/Work/ \
              --network=development \
              composer $params "$@"
          }

    - name: Add composer tools to PATH in .profile
      lineinfile:
        path: ~/.profile
        line: 'export PATH="$HOME/Work/Tools/composer:$PATH"'
        insertafter: EOF
        state: present