- hosts: localhost
  become: false

  vars_files:
    - ../../vars.yml

  tasks:
    - name: Install git
      become: true
      apt:
        name: git
        state: present

    - name: Configure user name
      command: git config --global user.name "{{ git_user_name }}"

    - name: Configure user email
      command: git config --global user.email "{{ git_user_email }}"

    - name: Configure file mode
      command: git config --global core.fileMode {{ git_core_file_mode }}

    - name: Configure main branch
      command: git config --global init.defaultBranch {{ git_init_default_branch }}

    - name: Create bashrc directory
      file: path=~/.bashrc.d state=directory

    - name: Create git bashrc
      file: path=~/.bashrc.d/git.sh state=touch

    - name: Add functions to bashrc
      blockinfile:
        path: ~/.bashrc.d/git.sh
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          repull () {
              git fetch --all
              git reset --hard origin/main
              git clean -f
          }

          repush () {
              git add .
              git commit --amend --no-edit
              git push -f
          }

          retag () {
              # Check if current folder is a git repo
              if [ ! -d .git ]; then
                  echo "Not a git repository"
                  exit 1
              fi

              # Add all files
              git add .

              # Amend last commit without changing the message
              git commit --amend --no-edit

              # Delete existing tag if it exists
              git tag -d 0.1.0 2>/dev/null
    
              # Create tag on the amended commit
              git tag -a 0.1.0 -m "Implemented first draft"
          }