- hosts: localhost
  become: yes

  tasks:
    - name: Increase the number of file watchers
      sysctl:
        name: fs.inotify.max_user_watches
        value: 1048576
        state: present
        reload: yes